name: "STL-Service"
services:
  user-management-service:
    container_name: user-management-service

    build:
      context: .
      dockerfile: Spring.Dockerfile

    volumes:
      - ./services/user-management-service:/app
    ports:
      - 8080:8080

  billing-service:
    container_name: billing-service

    build:
      context: .
      dockerfile: Spring.Dockerfile

    volumes:
      - ./services/billing-service:/app
    ports:
      - 8082:8082

  chat-service:
    container_name: chat-service

    build:
      context: .
      dockerfile: Spring.Dockerfile

    volumes:
      - ./services/chat-service:/app
    ports:
      - 8083:8083

  notification-service:
    container_name: notification-service

    build:
      context: .
      dockerfile: Spring.Dockerfile

    volumes:
      - ./services/notification-service:/app
    ports:
      - 8081:8081

  telco-service:
    container_name: telco-service

    build:
      context: .
      dockerfile: Spring.Dockerfile
    volumes:
      - ./services/telco-service:/app
    ports:
      - 8085:8085

  integration-esb:
    container_name: integration-esb

    build:
      context: .
      dockerfile: Spring.Dockerfile

    volumes:
      - ./services/integration-esb:/app
    ports:
      - 8084:8084
    depends_on:
      - kafka

  db:
    container_name: db

    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

    ports:
      - "3306:3306"
    volumes:
      - db_data_1:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin

    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD:

    ports:
      - "8090:80"
    volumes:
      - /sessions_1

  zoo:
    container_name: zoo

    image: zookeeper
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER: PLAINTEXT://:9092

      KAFKA_CREATE_TOPICS: "test:1:1"
    depends_on:
      - zoo

volumes:
  db_data_1:
