version: '3.8'
services:
  user-management-service:
    image: user-management-service
    build:
      context: .
      dockerfile: ./user-management-service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  notification-system:
    image: notification-system
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - user-management-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    networks:
      - microservices-network
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - microservices-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
